version: '3'
services:
  dotnet-server:
    build:
      context: ./
      dockerfile: ./greeter-service/Dockerfile
    image: greeter-service
    ports:
      - "5000:5000"
  envoy:
    build:
      context: ./greeter-gateway
      dockerfile: ./Dockerfile
    image: greeter-gateway
    ports:
      - "8080:8080"
    links:
      - dotnet-server
  angular-client:
    build:
        context: ./greeter-client
        dockerfile: ./Dockerfile
    image: greeter-client
    ports:
      - "4200:80"